# Generated by Django 5.2 on 2025-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('purchased', 'Purchased')], default='pending', max_length=20),
        ),
    ]
